### PR TITLE
fixes #30

### LINKED ISSUE #30: Broken formatting with new python.el (0.28)
Since the new update to the built-in python mode, `python-docstring-fill`does not work fully anymore.

The following code will not change when formatted with `python-docstring-fill`, python.el version 0.27.1:
```python
def fun(a):
    """
    Do something.

    :param a: do something with a
    """
```

When using python.el, version 0.28, `python-docstring-fill`will now format this code as such:
```python
def fun(a):
    """
 Do something.

      :param a: do something with a
        """
```

I'm now going to step through execution of the function to see if I can find the issue, but I may not be adept enough at elisp to debug it myself.

### PR DESCRIPTION
**Pull request by vale981**
credits to https://github.com/shabble

fixes #30

### CODE REVIEW

**Review by glyph — COMMENTED** [review]
Hmm. This still works for me. Is this emacs-version dependent? I might have missed something in the original discussion.

**Comment by vale981** [comment]
No clue tbh. I have only copied shabble's code :P.
It seems that python.el has to be above 0.28.

**Comment by timlod** [comment]
@glyph Indeed it should be `python.el` version dependent.
I get the issues on Emacs 27.1, for what it's worth. I've been using this fix, which works.
Do you have a setup with python.el 0.28 where you don't see the problem reported in my original issue?

**Comment by glyph** [comment]
@timlod Interesting. My build of Emacs 27.2 (from https://github.com/d12frosted/homebrew-emacs-plus ) includes a python.el that identifies itself as 0.26.1. How are you installing python.el?

**Comment by glyph** [comment]
Very confusing. ELPA lists https://elpa.gnu.org/packages/python.html as 0.28 which is an upgraded version, but then points at https://github.com/fgallina/python.el as the website which says the repo is no longer maintained.

**Comment by glyph** [comment]
I pushed an alternate fix (one that doesn't break on older / stock versions of python.el) in https://github.com/glyph/python-docstring-mode/commit/0dbc133cc9f207a448e59f3849c5e3ca51da7bd6 .  Hopefully this addresses everybody's issues!

**Pull request closed without merging**
